import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import java.io.ByteArrayOutputStream
import java.util.Properties

plugins {
    alias(libs.plugins.androidLibrary)
    alias(libs.plugins.kotlinAndroid)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.kotlinSerialization)
}

// ---------------------------------------------------------------------------
// Build-time secrets injection.
//
// Reads signaling + TURN secrets from `local.properties` (for local dev) or
// environment variables (for CI) and generates a Kotlin file that the shared
// config objects read at runtime.
//
// Priority per key: environment variable > local.properties > empty string.
// ---------------------------------------------------------------------------
val localSecretsProperties: Properties = Properties().apply {
    val file = rootProject.file("local.properties")
    if (file.exists()) file.inputStream().use { load(it) }
}

fun resolveBuildSecret(propertyKey: String, envKey: String): String {
    val fromEnv = System.getenv(envKey)?.trim().orEmpty()
    if (fromEnv.isNotBlank()) return fromEnv
    return localSecretsProperties.getProperty(propertyKey)?.trim().orEmpty()
}

// ---------------------------------------------------------------------------
// Version computation — mirrors androidApp/build.gradle.kts logic so the
// shared library can expose the same version constants.
// ---------------------------------------------------------------------------
val versionSchema = "release-v"
val defaultVersionName = "1.0.0"
val baseVersionCode = 1000

val computedVersionName: String = if (System.getenv("CI") == "true") {
    runCatching {
        val fromEnv = System.getenv("GITHUB_REF_NAME")?.trim().orEmpty()
        val branch = if (fromEnv.isNotEmpty()) {
            fromEnv
        } else {
            val stdout = ByteArrayOutputStream()
            exec {
                commandLine("sh", "-c", "git branch --show-current | tail -n 1")
                standardOutput = stdout
            }
            stdout.toString().trim()
        }
        when {
            branch.startsWith(versionSchema) -> branch.removePrefix(versionSchema)
            branch.isNotEmpty() -> branch
            else -> defaultVersionName
        }
    }.getOrElse { defaultVersionName }
} else {
    defaultVersionName
}

val computedVersionCode: Int = baseVersionCode + (System.getenv("GITHUB_RUN_NUMBER")?.toIntOrNull() ?: 0)

val generatedBuildSecretsDir: Provider<Directory> =
    layout.buildDirectory.dir("generated/buildSecrets/main/kotlin")

val generateBuildSecrets = tasks.register("generateBuildSecrets") {
    group = "build setup"
    description = "Generates GeneratedBuildSecrets.kt from local.properties / env vars."

    val signalingAuthToken = resolveBuildSecret("signaling.auth.token", "SIGNALING_AUTH_TOKEN")
    val signalingServerUrl = resolveBuildSecret("signaling.server.url", "SHAREX_REMOTE_SIGNALING_URL")
    val turnUrls = resolveBuildSecret("turn.urls", "SHAREX_TURN_URLS")
    val turnUsername = resolveBuildSecret("turn.username", "SHAREX_TURN_USERNAME")
    val turnCredential = resolveBuildSecret("turn.credential", "SHAREX_TURN_CREDENTIAL")

    // Declare inputs so Gradle regenerates when any secret or version changes.
    inputs.property("signalingAuthToken", signalingAuthToken)
    inputs.property("signalingServerUrl", signalingServerUrl)
    inputs.property("turnUrls", turnUrls)
    inputs.property("turnUsername", turnUsername)
    inputs.property("turnCredential", turnCredential)
    inputs.property("appVersionName", computedVersionName)
    inputs.property("appVersionCode", computedVersionCode)
    outputs.dir(generatedBuildSecretsDir)

    // Capture only serializable values for the configuration cache — no script references.
    val outputRootFile = generatedBuildSecretsDir.map { it.asFile }
    val versionName = computedVersionName
    val versionCode = computedVersionCode
    doLast {
        val outputDir = outputRootFile.get().resolve("com/teachmint/sharex/share/shared")
        outputDir.mkdirs()

        fun kotlinEscape(raw: String): String = raw
            .replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\$", "\\\$")

        val content = buildString {
            appendLine("// Auto-generated by :composeApp:generateBuildSecrets.")
            appendLine("// DO NOT EDIT. Values come from local.properties or environment variables.")
            appendLine("package com.teachmint.sharex.share.shared")
            appendLine()
            appendLine("internal object GeneratedBuildSecrets {")
            appendLine("    const val SIGNALING_AUTH_TOKEN: String = \"${kotlinEscape(signalingAuthToken)}\"")
            appendLine("    const val SIGNALING_SERVER_URL: String = \"${kotlinEscape(signalingServerUrl)}\"")
            appendLine("    const val TURN_URLS: String = \"${kotlinEscape(turnUrls)}\"")
            appendLine("    const val TURN_USERNAME: String = \"${kotlinEscape(turnUsername)}\"")
            appendLine("    const val TURN_CREDENTIAL: String = \"${kotlinEscape(turnCredential)}\"")
            appendLine("    const val APP_VERSION_NAME: String = \"${kotlinEscape(versionName)}\"")
            appendLine("    const val APP_VERSION_CODE: Int = $versionCode")
            appendLine("}")
        }
        outputDir.resolve("GeneratedBuildSecrets.kt").writeText(content)
    }
}

// Ensure every Kotlin compile task waits for secret generation.
tasks.configureEach {
    if (name.startsWith("compile") && name.contains("Kotlin", ignoreCase = true)) {
        dependsOn(generateBuildSecrets)
    }
}

kotlin {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_11)
    }
}

android {
    namespace = "com.teachmint.sharex"
    compileSdk = libs.versions.android.compileSdk.get().toInt()
    ndkVersion = "27.0.12077973"

    sourceSets.getByName("main") {
        java.srcDir(generatedBuildSecretsDir)
    }

    defaultConfig {
        minSdk = libs.versions.android.minSdk.get().toInt()
        targetSdk = libs.versions.android.targetSdk.get().toInt()
        consumerProguardFiles("consumer-rules.pro")

        // Configure NDK for native RTP receiver
        ndk {
            abiFilters.addAll(listOf("arm64-v8a", "armeabi-v7a", "x86", "x86_64"))
        }

        externalNativeBuild {
            cmake {
                cppFlags.add("-std=c++17")
                arguments.addAll(listOf(
                    "-DANDROID_STL=c++_shared",
                    "-DANDROID_PLATFORM=android-21",
                    // NDK r27 needs this explicit switch to emit 16 KB-compatible ELF segments.
                    "-DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON"
                ))
            }
        }
    }

    // Configure external native build
    externalNativeBuild {
        cmake {
            path = file("CMakeLists.txt")
            version = "3.22.1"
        }
    }

    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
            excludes += "META-INF/versions/9/OSGI-INF/MANIFEST.MF"
        }
    }
    buildTypes {
        getByName("debug") {
            isMinifyEnabled = false
        }
        getByName("release") {
            // R8 must only run on the app module (androidApp), not the library.
            // The app's R8 pass sees the full dependency graph and handles all
            // shrinking, optimization, and obfuscation for the final APK.
            // Running R8 here double-minifies Compose-generated bytecode and
            // breaks cross-module @Composable method dispatch at runtime.
            isMinifyEnabled = false
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
    buildFeatures {
        compose = true
    }
}

dependencies {
    // Compose (androidx) — api so :androidApp compiles against them transitively.
    api(platform(libs.androidx.compose.bom))
    api(libs.androidx.compose.runtime)
    api(libs.androidx.compose.foundation)
    api(libs.androidx.compose.material3)
    api(libs.androidx.compose.ui)
    api(libs.androidx.compose.materialIconsExtended)
    implementation(libs.androidx.compose.uiToolingPreview)
    debugImplementation(libs.androidx.compose.uiTooling)

    api(libs.androidx.lifecycle.viewmodelCompose)
    api(libs.androidx.lifecycle.runtimeCompose)
    api(libs.androidx.navigation.compose)
    api(libs.androidx.activity.compose)
    implementation(libs.androidx.core.ktx)

    api(libs.kotlinx.coroutines.core)
    implementation(libs.kotlinx.serialization.json)

    // Networking
    implementation(libs.ktor.client.core)
    implementation(libs.ktor.client.websockets)
    implementation(libs.ktor.client.content.negotiation)
    implementation(libs.ktor.serialization.kotlinx.json)
    implementation(libs.ktor.client.okhttp)
    implementation(libs.ktor.server.core)
    implementation(libs.ktor.server.cio)
    implementation(libs.ktor.server.websockets)

    // WebRTC
    implementation(libs.webrtc.kmp.android)

    // QR + Lottie
    implementation(libs.zxing.core)
    implementation(libs.compottie)

    // V-003: EncryptedSharedPreferences for secure credential storage
    implementation(libs.androidx.security.crypto)

    // AirPlay receiver dependencies
    implementation(libs.bouncycastle)
    implementation(libs.dd.plist)
    implementation(libs.jmdns)

    // Firebase
    implementation(platform(libs.firebase.bom))
    implementation(libs.firebase.config)
    implementation(libs.firebase.crashlytics)

    debugImplementation("com.github.chuckerteam.chucker:library:4.0.0")
    releaseImplementation("com.github.chuckerteam.chucker:library-no-op:4.0.0")

    testImplementation(libs.kotlin.testJunit)
    testImplementation(libs.junit)
}
