name: "QA: macOS Desktop Build"

on:
  workflow_dispatch:

jobs:
  build:
    name: Package macOS DMG (QA)
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Write secrets to local.properties
        run: |
          cat >> local.properties <<EOF
          signaling.auth.token=${{ secrets.SIGNALING_AUTH_TOKEN }}
          signaling.server.url=${{ secrets.SIGNALING_SERVER_WSS_URL }}
          turn.urls=${{ secrets.SHAREX_TURN_URLS }}
          turn.username=${{ secrets.SHAREX_TURN_USERNAME }}
          turn.credential=${{ secrets.SHAREX_TURN_CREDENTIAL }}
          EOF

      - name: Package DMG (macOS Desktop)
        run: ./gradlew :composeApp:packageDmg

      - name: Upload Artifact
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: TeachmintShareX-macOS-DMG-QA
          path: composeApp/build/compose/binaries/main/dmg/*.dmg

      - name: Google Chat Notification Action
        if: always()
        uses: SimonScholz/google-chat-action@v1.1.0
        with:
          webhookUrl: ${{ secrets.GCHAT_NOTIFICATION }}
          jobStatus: ${{ job.status }}
          title: "macOS Desktop Build (QA)"
          subtitle: 'Triggered by: ${{ github.triggering_actor }}'
          imageUrl: https://storage.googleapis.com/tm-assets/images/dark/teachmint-collapse-logo.svg         
          additionalSections: '[
            {
                "header": "Deployment Details", 
                "collapsible": false, 
                "widgets": [
                    {
                        "decoratedText": {
                            "startIcon": {
                                "knownIcon": "STAR"
                            },
                            "text": "<b>Download DMG:</b> <a href=\"${{ steps.upload_artifact.outputs.artifact-url }}\">Download macOS Artifact</a>",
                            "wrapText": true
                        }        
                    },
                    {
                        "decoratedText": {
                            "startIcon": {
                                "knownIcon": "STAR"
                            },
                            "text": "<b>Build Run:</b> <a href=\"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\">View Workflow Run & Artifacts</a>",
                            "wrapText": true
                        }        
                    }                                          
                ]
            }
          ]'
